### ISSUE TITLE
AttributeError: '_TTGlyphCFF' object has no attribute 'decompile'

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/compreffor#2]
First of all, thank you very much for open-sourcing this library.

I am trying to run the python-only version, "pyCompressor.py", on some CFF-OTF fonts of ours.
I'm running python 2.7.9 on OS X. FontTools is checked out at the latest commit (c0eb70308b47b20137fe74d421d29d81e095f68f).
I have previously used pyftsubset to --desubroutinize the fonts.

When I run python compreffor on the fonts, I always get an AttributeError exception:
```python
$ python pyCompressor.py /Users/cosimolupo/Desktop/LushHandwritten_Rg.subset.otf 
Traceback (most recent call last):
  File "pyCompressor.py", line 1127, in <module>
    main(**kwargs)
  File "pyCompressor.py", line 1071, in main
    handle_font(filename)
  File "pyCompressor.py", line 1048, in handle_font
    compreffor.compress()
  File "pyCompressor.py", line 494, in compress
    n_locals)
  File "pyCompressor.py", line 588, in iterative_encode
    sf = SubstringFinder(glyph_set, verbose=self.verbose)
  File "pyCompressor.py", line 253, in __init__
    self.process_chstrings(glyph_set)
  File "pyCompressor.py", line 270, in process_chstrings
    char_string.decompile()
AttributeError: '_TTGlyphCFF' object has no attribute 'decompile'
```

`_TTGlyphCFF`, as defined in `fontTools.ttLib.__init__`, does not have a `decompile` method. But its `self._glyph` attribute (i.e. the wrapped `T2CharString` object) does have one. So it seems like some changes have occurred in upstream fontTools since the time pyCompressor.py:270 was originally written.

However, even if I change the previous line (269) so that it accesses the `_glyph` attribute:

```diff
        for k in self.glyph_set_keys:
-            char_string = glyph_set[k]
+            char_string = glyph_set[k]._glyph
            char_string.decompile()
            program = []
```

then, the charstring can be decompiled, but the following assertion fails with:

```python
Traceback (most recent call last):
  File "pyCompressor.py", line 1127, in <module>
    main(**kwargs)
  File "pyCompressor.py", line 1071, in main
    handle_font(filename)
  File "pyCompressor.py", line 1048, in handle_font
    compreffor.compress()
  File "pyCompressor.py", line 494, in compress
    n_locals)
  File "pyCompressor.py", line 588, in iterative_encode
    sf = SubstringFinder(glyph_set, verbose=self.verbose)
  File "pyCompressor.py", line 253, in __init__
    self.process_chstrings(glyph_set)
  File "pyCompressor.py", line 276, in process_chstrings
    i == len(char_string.program) - 1
AssertionError
```

I'm afraid I don't know much about how CFF works, so I don't understand the logic of this assertion. I don't think there's anything wrong with the font files, as that assertion is raised on any font I've run through pyCompressor.py. If I comment out the assertion, then the script completes without errors. However, there must have been a reason if @samfishman put an assert there.

Btw, the cxxCompressor.py (both when using subprocess and the dynamic library) seem to be working fine. It's only the python version which has the above mentioned problems.

Thank you again,
Cheers.

Cosimo

**Comment by samfishman** [comment]
I believe that the assertion is actually wrong, it should be doing something closer to
```py
assert tok not in ('callsubr', 'callgsubr')
```
because it means to check that there are no subroutines in the input font (so no `call(g)subr`s). The loop in question is running over the charstrings of the glyphs, so if the font is valid, there should never be a `return` instruction. Additionally, if the font is valid `endchar` can only occur at the last position in the charstring. I think I wanted to assert some simple font validity conditions but messed it up (there should _never_ be subr calls, but the current assertion allows them at the end of the charstring). If we wanted to keep some of those validity conditions, the assertion could be changed to
```py
assert tok not in ('callsubr', 'callgsubr', 'return')
assert tok != 'endchar' or i == len(char_string.program) - 1
```
But I don't think that's necessary.

However, this doesn't explain why the assertion failed assuming you passed in a valid, desubroutinized font resource. Can you change the (current, not my corrected version) assertion into an `if` and print out the decompiled charstring it's failing on?

**Comment by anthrotype** [comment]
Thanks for the clarification.
I'll send a PR to fix the AttributeError, and also to change the assertion as you suggested.

The file I was using in my tests turned out to contain subroutines -- I apologise. I shall try again by recompiling the fonts with subroutinization disabled.

**Comment by behdad** [comment]
Anything to be done here?

**Comment by anthrotype** [comment]
cool, thanks
